version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - java -version
      - echo Build started on `date`
      - NODE_OPTIONS="--max-old-space-size=4096"
      - chmod +x gradlew
      - ./gradlew clean build
  post_build:
    commands:
      - echo Build completed on `date`


artifacts:
  files:
    - server/build/libs/starterapp-1.0.0-SNAPSHOT.jar


